services:
  app:
    build: .
    container_name: sibeta_app
    ports:
      - "5009:5009"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/sibeta

  mongo:
    image: mongo:4.4
    container_name: sibeta_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: